wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.13
    cli_version: 0.16.3
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1759043389.408493
    t:
      1:
      - 5
      - 6
      - 7
      - 8
      - 53
      - 55
      2:
      - 5
      - 6
      - 7
      - 8
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.13
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
