rf:
  random:
    n_estimators: [200, 400]
    max_depth: [10, 15]
    min_samples_split: [10, 20]
    min_samples_leaf: [5, 10]
    max_features: ["sqrt", 0.7]
  grid:
    n_estimators: [200, 400]
    max_depth: [10, 15]
    min_samples_split: [10]
    min_samples_leaf: [5]
    max_features: ["sqrt"]

lgbm:
  random:
    n_estimators: [500, 1000]
    learning_rate: [0.05, 0.1]
    num_leaves: [31, 63]
    min_child_samples: [20, 50]
    feature_fraction: [0.8, 1.0]
    bagging_fraction: [0.8, 1.0]
    lambda_l2: [0.0, 1.0]
  grid:
    n_estimators: [500, 1000]
    learning_rate: [0.05, 0.1]
    num_leaves: [31, 63]
    min_child_samples: [20]
    lambda_l2: [0.0, 1.0]

xgb:
  random:
    n_estimators: [500, 1000]
    max_depth: [6, 8]
    learning_rate: [0.05, 0.1]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]
    min_child_weight: [1, 5]
    reg_lambda: [1.0, 2.0]
  grid:
    n_estimators: [500, 1000]
    max_depth: [6, 8]
    learning_rate: [0.05, 0.1]
    subsample: [0.8]
    colsample_bytree: [0.8]
    reg_lambda: [1.0]

cat:
  random:
    depth: [6, 8]
    learning_rate: [0.05, 0.1]
    l2_leaf_reg: [3, 5]
    iterations: [500, 1000]
    subsample: [0.8, 1.0]
  grid:
    depth: [6, 8]
    learning_rate: [0.05, 0.1]
    l2_leaf_reg: [3]
    iterations: [500, 1000]

ridge:
  random:
    alpha: [0.1, 1.0, 10.0]
    fit_intercept: [true, false]
  grid:
    alpha: [1.0, 10.0]
    fit_intercept: [true]

lasso:
  random:
    alpha: [0.01, 0.1, 1.0]
    fit_intercept: [true, false]
  grid:
    alpha: [0.01, 0.1]
    fit_intercept: [true]

linear:
  grid:
    fit_intercept: [true, false]
  random:
    fit_intercept: [true, false]